pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk 'JDK17'
    }

    stages {

        stage('Checkout') {
            steps {
                echo "Cloning source code..."
                git branch: 'main', url: 'https://github.com/jassu810/ecommerce-devops.git'
            }
        }

        stage('Build') {
            steps {
                echo "Building application..."
                sh 'mvn clean compile'
            }
        }

        stage('Test') {
            steps {
                echo "Running test cases..."
                sh 'mvn test'
            }
        }

        stage('Code Quality - SonarQube') {
            steps {
                echo "Running SonarQube analysis..."
                sh 'mvn sonar:sonar'
            }
        }

        stage('Package') {
            steps {
                echo "Packaging application..."
                sh 'mvn package -DskipTests'
            }
        }

        stage('Archive Artifacts') {
            steps {
                echo "Archiving build artifacts..."
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            }
        }
    }

    post {
        always {
            echo "Pipeline execution completed."
        }
        success {
            echo "Build successful ✅"
        }
        failure {
            echo "Pipeline failed ❌"
        }
    }
}